#!/usr/bin/env bash

REPO_NAME="mobydock"

# Check out the newest version of the code.
 export GIT_WORK_TREE="/var/git/${REPO_NAME}"
# --- NO GOOD - this does not work :> export GIT_WORK_TREE="/var/git/MobyDock/${REPO_NAME}"
 export GIT_BUILD_TREE="/var/git/mobydock/${REPO_NAME}"
git checkout -f

TAG="$(git log --pretty=format:'%h' -n 1)"
FULL_COMMIT_TAG="${REPO_NAME}:${TAG}"
echo "FULL_COMMIT_TAG=${FULL_COMMIT_TAG}"
FULL_LATEST_TAG="${REPO_NAME}:latest"

echo " *** Build the image with the proper commit tag."
# echo "docker build -t ${FULL_LATEST_TAG} ${GIT_WORK_TREE}"
# docker build -t "${FULL_LATEST_TAG}" "${GIT_WORK_TREE}"
echo "docker build -t ${FULL_LATEST_TAG} ${GIT_BUILD_TREE}"
docker build -t "${FULL_LATEST_TAG}" "${GIT_BUILD_TREE}"


echo " *** Get the Docker ID of the last built image."
echo " DOCKER_ID=$(docker images -q ${REPO_NAME} | head -1)"
DOCKER_ID="$(docker images -q ${REPO_NAME} | head -1)"

#echo " *** Tag a latest version based off a commit tag."
#docker tag -f "${DOCKER_ID}" "${FULL_LATEST_TAG}"

echo "Restarting ${REPO_NAME}"
docker stop "${REPO_NAME}"

echo " *** Removing untagged Docker images (may take a while)"
docker rmi $(docker images --quiet --filter "dangling=true")
